### ISSUE TITLE
How to Run Juypter Notebook?

### ISSUE THREAD

**Issue by BigSalmon2** [chrisdonahue/ilm#1]
It continually says I am missing certain things. I am new, and would really like to try it. Could I please have some guidance?

**Comment by chrisdonahue** [comment]
Could you elaborate a bit? What's the issue specifically?

Likely you need to `pip install -e .` the `ilm` package such that it can be recognized in your Jupyter notebook

**Comment by BigSalmon2** [comment]
Thank you for your quick response. I should mention that I am actually using a Google Colab Notebook. I am sorry for the lack of clarity.

Upon running this, I get the error message: 

```
if MODEL_DIR is None:
    !wget -nc --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1oYFLxkX6mWbmpEwQH8BmgE7iKix2W0zU' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1oYFLxkX6mWbmpEwQH8BmgE7iKix2W0zU" -O /tmp/ilm/eval_repro/models/sto_ilm/pytorch_model.bin && rm -rf /tmp/cookies.txt
    !wget -nc --no-check-certificate 'https://docs.google.com/uc?export=download&id=15JnXi7L6LeEB2fq4dFK2WRvDKyX46hVi' -O /tmp/ilm/eval_repro/models/sto_ilm/config.json
    MODEL_DIR = '/tmp/ilm/eval_repro/models/sto_ilm'`
```

`/tmp/ilm/eval_repro/models/sto_ilm/pytorch_model.bin: No such file or directory, /tmp/ilm/eval_repro/models/sto_ilm/config.json: No such file or directory`

It seems that "!wget" is not working, but I am not so sure how I can fix that.

**Comment by chrisdonahue** [comment]
Thanks for bringing this to our attention! I made a Google Colab-friendly version of the inference notebook. Note that you may have to restart your runtime after installing the dependencies

https://colab.research.google.com/drive/1So95M0hHefyNm_eELglCna_ZayoDX6KV?usp=sharing

Does this fix the issue you were having?

**Comment by BigSalmon2** [comment]
Thank you so much. That fixed everything!
