### ISSUE TITLE
How to adapt to new pre-trained models?

### ISSUE THREAD

**Issue by xingbow** [chrisdonahue/ilm#5]
Is it easy to use the framework to adapt to another pre-trained model? For example, BART?

**Comment by xingbow** [comment]
If I want to use BART for multi-level text infilling fine-tuning. Which part of the code should I check and revise? Can you provide some hints?

**Comment by chrisdonahue** [comment]
The main thing you'll have to modify is the [`tokenizer_util.py` file](https://github.com/chrisdonahue/ilm/blob/master/ilm/tokenize_util.py). You'll also have to do some modification to the [training script](https://github.com/chrisdonahue/ilm/blob/master/train_ilm.py).

How does BART tokenize? This modification process will be much easier if it's trivial to align BART tokens to characters. Doing so is not super straightforward with GPT-2 (hence the large amount of code) but may be easier for BART.

**Comment by xingbow** [comment]
> The main thing you'll have to modify is the [`tokenizer_util.py` file](https://github.com/chrisdonahue/ilm/blob/master/ilm/tokenize_util.py). You'll also have to do some modification to the [training script](https://github.com/chrisdonahue/ilm/blob/master/train_ilm.py).
> 
Thanks. I think this piece of information is very helpful ;)

> How does BART tokenize? This modification process will be much easier if it's trivial to align BART tokens to characters. Doing so is not super straightforward with GPT-2 (hence the large amount of code) but may be easier for BART.

I think the BART tokenizer won't differ much from GPT-2 and it is built based on the GPT-2 library.
